// Todo el texto y los datos de la web. Edita aquí y ejecuta: node scripts/build.mjs

export const SITE = {
  name: 'Escuela de Danza Manuela',
  short: 'Danza Manuela',
  url: 'https://sefiro888.github.io/escueladanzamanuela/',
  slogan: 'Baila con el corazón, los pies te seguirán',
  phone: '661 77 07 18',
  phoneIntl: '+34661770718',
  whatsapp: '34661770718',
  email: 'escueladedanzamanuela@gmail.com',
  instagram: 'https://www.instagram.com/escueladedanzamanuela/',
  instagramUser: '@escueladedanzamanuela',
  facebook: 'https://www.facebook.com/p/Escuela-de-Danza-Manuela-100031771106340/',
  maps: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0xd422f901deea2ab:0x269bf4174a96fa72',
  reviewsUrl: 'https://www.google.com/search?kgmid=/g/11g8dl5ddd&q=Escuela+de+Danza+Manuela',
  rating: '4,7',
  ratingValue: 4.7,
  reviewCount: 21,
  followers: '1,6 mil',
  sedes: [
    {
      id: 'canillejas',
      name: 'Sede Canillejas',
      street: 'Av. de Canillejas a Vicálvaro, 139',
      city: 'San Blas-Canillejas · 28022 Madrid',
      maps: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0xd422f901deea2ab:0x269bf4174a96fa72',
      embed: 'https://www.google.com/maps?q=Av.+de+Canillejas+a+Vic%C3%A1lvaro,+139,+28022+Madrid&output=embed',
      note: 'Sede principal',
    },
    {
      id: 'longares',
      name: 'Sede Longares',
      street: 'C/ Longares, 48',
      city: 'San Blas-Canillejas · Madrid',
      maps: 'https://www.google.com/maps/search/?api=1&query=Calle+de+Longares+48+Madrid',
      embed: 'https://www.google.com/maps?q=Calle+de+Longares+48,+Madrid&output=embed',
      note: 'Segunda sala',
    },
  ],
}

export const ANNOUNCE = [
  'Nuevo curso en marcha · pregunta por plazas',
  'Clases para peques, jóvenes y adultos',
  '4,7 ★ en Google',
  'Dos sedes en San Blas-Canillejas',
  'Baile nupcial a medida',
  'Subcampeonas de España con Liryc y Blackfunk',
  'Escríbenos por WhatsApp: 661 77 07 18',
]

// Grupos del menú
export const GROUPS = [
  { id: 'clasico', name: 'Clásico y expresión', classes: ['ballet', 'baile-moderno', 'flamenco'] },
  { id: 'urbano', name: 'Urbano y escena', classes: ['funky', 'comercial', 'k-pop'] },
  { id: 'ritmo', name: 'Ritmo y social', classes: ['salsa', 'zumba', 'country'] },
]

const commonWear = {
  urbano: ['Ropa cómoda y holgada (chándal, cargo, camiseta)', 'Zapatillas deportivas limpias, mejor con suela lisa', 'Botella de agua', 'Pelo recogido y muchas ganas'],
}

export const CLASSES = [
  {
    slug: 'flamenco',
    name: 'Flamenco',
    menu: 'Compás, taconeo y arte',
    tagline: 'Fuerza, compás y duende en cada movimiento.',
    title: 'Flamenco con <em>duende</em>',
    group: 'clasico',
    tags: ['peques', 'jovenes', 'adultos'],
    ages: 'Desde 4 años · infantil y adultos',
    level: 'Iniciación a avanzado',
    duration: '60 min',
    energy: 4,
    photo: 'flamenco',
    decor: 'flamenco',
    alt: 'Profesora y alumnas de varias edades bailando flamenco con bata de volantes en una sala luminosa',
    highlight: '«Un lujo al alcance de todos con la mejor profesional de flamenco de Madrid» — reseña en Google',
    lead: 'El flamenco es la casa de Manuela. Aquí se aprende desde el primer día a escuchar el compás, a colocar los brazos con intención y a sacar fuerza de los pies sin perder la elegancia.',
    intro: [
      'Trabajamos la técnica de zapateado, el braceo, las vueltas y el uso de la falda y el mantón, siempre con la música como guía. Las niñas y niños empiezan jugando con las palmas y el ritmo; los adultos descubren que nunca es tarde para sentir una sevillana o una rumba.',
      'A lo largo del curso montamos coreografías por palos —sevillanas, rumbas, tangos, alegrías o bulerías según el nivel— que luego lucimos en el festival de fin de curso y en actuaciones por Madrid.',
    ],
    learn: [
      ['Compás y palmas', 'Entender los tiempos y acentos de cada palo, y llevarlos con las palmas antes de llevarlos a los pies.'],
      ['Zapateado', 'Planta, tacón, punta y golpe: técnica limpia, progresiva y sin dañar las rodillas.'],
      ['Braceo y manos', 'Brazos largos, muñecas vivas y floreo de manos: la parte más expresiva del baile.'],
      ['Sevillanas', 'Las cuatro sevillanas completas para disfrutarlas en cualquier feria o boda.'],
      ['Falda y mantón', 'Manejo de los complementos que dan al flamenco su movimiento y su color.'],
      ['Expresión y duende', 'Mirada, actitud y presencia escénica para bailar con verdad.'],
    ],
    session: [
      ['10 min', 'Calentamiento', 'Activación de tobillos, rodillas y espalda con ritmo flamenco de fondo.'],
      ['15 min', 'Técnica', 'Ejercicios de zapateado y braceo por niveles, frente al espejo.'],
      ['25 min', 'Coreografía', 'Avanzamos en el baile del trimestre por frases, con la música real.'],
      ['10 min', 'Pasada final', 'Bailamos todo lo aprendido y estiramos para cerrar.'],
    ],
    forWho: ['Peques que quieren descubrir el ritmo jugando', 'Jóvenes con ganas de técnica y escenario', 'Adultos que siempre quisieron aprender sevillanas', 'Quien busca un ejercicio completo con mucho arte'],
    wear: ['Falda de flamenco o falda amplia (para empezar vale una falda larga cómoda)', 'Zapatos de flamenco con clavos; los primeros días, zapato de tacón ancho', 'Ropa ajustada arriba para ver la colocación', 'Abanico o mantón cuando lo indique la profesora'],
    levels: [
      ['Iniciación', 'Postura, palmas, primeras sevillanas y zapateados sencillos.'],
      ['Intermedio', 'Rumbas y tangos, vueltas, braceo con más recorrido y trabajo de falda.'],
      ['Avanzado', 'Alegrías o bulerías, escobillas de zapateado y coreografía de escenario.'],
    ],
    faq: [
      ['¿Necesito zapatos de flamenco desde el primer día?', 'No. Para las primeras clases basta un zapato con tacón ancho y cómodo. Cuando veas que te engancha, te aconsejamos qué modelo comprar.'],
      ['¿Hay grupos solo para adultos?', 'Sí. Los adultos tienen su propio grupo, para que cada persona avance a su ritmo y sin presión.'],
      ['¿Se baila en público?', 'Quien quiere, sí: festival de fin de curso, certámenes y actuaciones. Nunca es obligatorio.'],
    ],
  },
  {
    slug: 'ballet',
    name: 'Ballet',
    menu: 'Clásico, lírico y puntas',
    tagline: 'Ligereza, música y precisión en cada línea.',
    title: 'Ballet <em>clásico</em>',
    group: 'clasico',
    tags: ['peques', 'jovenes', 'adultos'],
    ages: 'Desde 4 años · por niveles',
    level: 'Predanza a puntas',
    duration: '60 min',
    energy: 3,
    photo: 'ballet',
    decor: 'ballet',
    alt: 'Niña y bailarinas adultas en la barra de ballet de un estudio luminoso con espejos',
    highlight: 'En la escuela se descubre la magia del ballet desde pequeñita: incluso las más pequeñas aprenden a expresarse con el cuerpo.',
    lead: 'El ballet es la base de casi todas las danzas: enseña a colocar el cuerpo, a respirar con la música y a moverse con una ligereza que se nota en todo lo demás.',
    intro: [
      'En la escuela trabajamos clásico, lírico y puntas. Las más pequeñas empiezan con predanza, a través del juego y la música; después llega la barra, el centro, los giros y los saltos, siempre respetando el ritmo de cada alumna y alumno.',
      'Cuando el cuerpo está preparado —y solo entonces— llega el trabajo de puntas. Y para quien quiere expresarse más libremente, el lírico une la técnica del ballet con la emoción de la danza contemporánea.',
    ],
    learn: [
      ['Colocación', 'Postura, rotación y alineación: la base para bailar sin lesiones.'],
      ['Barra', 'Pliés, tendus, dégagés, ronds de jambe… los ejercicios de siempre, bien explicados.'],
      ['Centro y adagio', 'Equilibrio, control y líneas largas sin apoyo.'],
      ['Giros y saltos', 'Pirouettes, sautés y allegro para ganar fuerza y elasticidad.'],
      ['Puntas', 'Fortalecimiento previo y técnica de puntas cuando llega el momento.'],
      ['Lírico', 'Coreografías emotivas que mezclan técnica clásica y expresión.'],
    ],
    session: [
      ['15 min', 'Barra', 'Calentamiento técnico con la secuencia clásica de ejercicios.'],
      ['15 min', 'Centro', 'Adagio, port de bras y equilibrios sin apoyo.'],
      ['20 min', 'Diagonales', 'Giros, saltos y desplazamientos por la sala.'],
      ['10 min', 'Reverencia', 'Estiramientos, flexibilidad y la reverencia final.'],
    ],
    forWho: ['Peques desde 4 años (predanza)', 'Niñas y niños que quieren una base técnica sólida', 'Jóvenes que se preparan para lírico y puntas', 'Adultos que vuelven al ballet o empiezan de cero'],
    wear: ['Maillot y medias rosas (o ropa ajustada los primeros días)', 'Zapatillas de media punta', 'Falda de gasa opcional', 'Pelo recogido en moño'],
    levels: [
      ['Predanza', 'Para 4–6 años: psicomotricidad, música y primeros pasos de ballet jugando.'],
      ['Clásico', 'Barra, centro y diagonales con progresión por cursos.'],
      ['Lírico y puntas', 'Técnica avanzada, trabajo de puntas y coreografía expresiva.'],
    ],
    faq: [
      ['¿Desde qué edad pueden empezar?', 'Desde los 4 años en predanza. A partir de ahí se pasa a clásico por niveles.'],
      ['¿Cuándo se empieza con puntas?', 'Cuando la profesora ve que pies, tobillos y espalda están preparados. Nunca antes de tiempo.'],
      ['¿Hay ballet para adultos?', 'Sí. Es una clase perfecta para ganar postura, flexibilidad y calma.'],
    ],
  },
  {
    slug: 'funky',
    name: 'Funky',
    menu: 'Actitud y groove urbano',
    tagline: 'Energía, actitud y ritmo para moverte con libertad.',
    title: 'Funky con <em>actitud</em>',
    group: 'urbano',
    tags: ['peques', 'jovenes', 'adultos'],
    ages: 'Infantil y adultos',
    level: 'Todos los niveles',
    duration: '60 min',
    energy: 5,
    photo: 'funky',
    decor: 'funky',
    alt: 'Grupo de niños y adultos bailando funky con ropa urbana rosa y negra en un estudio',
    highlight: 'Nuestro grupo Blackfunk quedó segundo de su categoría en el Campeonato de España.',
    lead: 'El funky es la clase donde más se ríe y más se suda. Coreografías urbanas con mucho groove, música actual y una energía que se contagia desde el primer minuto.',
    intro: [
      'Mezclamos pasos de hip hop, funk y danza urbana en coreografías dinámicas, pensadas para que cada persona saque su estilo. Hay grupos infantiles y de adultos, y todos terminan la clase con una sonrisa.',
      'Para quien quiere más, el funky es la puerta de entrada a los grupos de competición de la escuela, como Blackfunk, que se subió al podio del Campeonato de España.',
    ],
    learn: [
      ['Groove', 'El rebote y la cadencia que hacen que el baile urbano se vea natural.'],
      ['Aislamientos', 'Mover cabeza, pecho y cadera por separado para ganar control.'],
      ['Pasos base', 'Los pasos clásicos del funk y el hip hop, bien hechos.'],
      ['Coreografía', 'Memoria, musicalidad y sincronía en grupo.'],
      ['Actitud', 'Presencia, mirada y estilo propio sobre el escenario.'],
      ['Freestyle', 'Momentos de improvisación para perder la vergüenza.'],
    ],
    session: [
      ['10 min', 'Warm up', 'Calentamiento con música y ejercicios de groove.'],
      ['15 min', 'Pasos', 'Técnica urbana: aislamientos, pasos base y variaciones.'],
      ['25 min', 'Coreo', 'Montamos la coreografía de la semana por bloques.'],
      ['10 min', 'Show', 'La bailamos en grupos, como si fuera el escenario.'],
    ],
    forWho: ['Peques con mucha energía', 'Adolescentes que quieren bailar la música que escuchan', 'Adultos que buscan desconectar y sudar', 'Familias: hay grupos infantiles y de adultos'],
    wear: commonWear.urbano,
    levels: [
      ['Infantil', 'Coreografías divertidas y adaptadas, con mucho juego y ritmo.'],
      ['Juvenil', 'Más técnica urbana, estilo y coreografías con más exigencia.'],
      ['Adultos', 'Para empezar o retomar: se baila, se suda y se disfruta.'],
    ],
    faq: [
      ['¿Hace falta experiencia?', 'Ninguna. Las coreografías se adaptan al grupo y se explican paso a paso.'],
      ['¿Hay grupos de competición?', 'Sí. Quien quiere ir más allá puede formar parte de los grupos que compiten, como Blackfunk.'],
      ['¿Hay funky para adultos?', 'Sí, la escuela tiene funky infantil y funky para adultos.'],
    ],
  },
  {
    slug: 'baile-moderno',
    name: 'Baile moderno',
    menu: 'Contemporáneo y lírico',
    tagline: 'Movimiento actual para expresarte a tu manera.',
    title: 'Moderno y <em>contemporáneo</em>',
    group: 'clasico',
    tags: ['jovenes', 'adultos'],
    ages: 'Desde 8 años · jóvenes y adultos',
    level: 'Todos los niveles',
    duration: '60 min',
    energy: 3,
    photo: 'baile-moderno',
    decor: 'baile-moderno',
    alt: 'Bailarines de danza contemporánea con ropa negra en un estudio iluminado en rosa',
    highlight: 'El grupo Liryc de la escuela fue segundo de su categoría en el Campeonato de España.',
    lead: 'Suelo, respiración, peso y emoción. El baile moderno y contemporáneo es la danza más libre: no se trata de hacer los pasos perfectos, sino de contar algo con el cuerpo.',
    intro: [
      'Trabajamos técnica contemporánea —caídas, espirales, trabajo de suelo, impulsos— junto a la expresividad del lírico, con coreografías sobre música actual que emocionan al bailarlas y al verlas.',
      'Es la clase ideal para quien viene del ballet y quiere soltarse, y también para quien nunca ha bailado y busca una forma creativa de moverse.',
    ],
    learn: [
      ['Trabajo de suelo', 'Rodar, caer y levantarse con fluidez y sin miedo.'],
      ['Respiración', 'Usar el aire para dar impulso y suspensión al movimiento.'],
      ['Peso y espirales', 'Movimientos orgánicos que nacen del centro del cuerpo.'],
      ['Improvisación', 'Ejercicios guiados para encontrar tu forma de moverte.'],
      ['Lírico', 'Coreografía emotiva con base técnica.'],
      ['Interpretación', 'Llevar una emoción del cuerpo al público.'],
    ],
    session: [
      ['10 min', 'Conciencia', 'Calentamiento suave, respiración y movilidad.'],
      ['15 min', 'Técnica', 'Suelo, giros y desplazamientos contemporáneos.'],
      ['25 min', 'Creación', 'Coreografía o improvisación guiada.'],
      ['10 min', 'Cierre', 'Estiramientos y vuelta a la calma.'],
    ],
    forWho: ['Jóvenes que quieren expresarse', 'Bailarinas de ballet que buscan más libertad', 'Adultos creativos sin experiencia previa', 'Quien busca una actividad física consciente'],
    wear: ['Ropa cómoda que permita moverse en el suelo', 'Descalzo, con calcetines o con medias de contemporáneo', 'Rodilleras opcionales', 'Agua'],
    levels: [
      ['Iniciación', 'Primeras herramientas de contemporáneo y mucha exploración.'],
      ['Intermedio', 'Más técnica de suelo, giros y frases largas.'],
      ['Grupo Liryc', 'Coreografía lírica de nivel y preparación de certámenes.'],
    ],
    faq: [
      ['¿Es muy distinto del ballet?', 'Comparte la base técnica, pero usa el suelo, el peso y una música mucho más variada.'],
      ['¿Se baila descalzo?', 'Normalmente sí, o con calcetines. Te lo indicamos el primer día.'],
      ['¿Puedo empezar de adulto?', 'Claro. Es de las disciplinas más agradecidas para empezar de adulto.'],
    ],
  },
  {
    slug: 'comercial',
    name: 'Comercial',
    menu: 'Coreografías de videoclip',
    tagline: 'Coreografías con presencia y energía de escenario.',
    title: 'Comercial de <em>videoclip</em>',
    group: 'urbano',
    tags: ['jovenes', 'adultos'],
    ages: 'Desde 10 años · jóvenes y adultos',
    level: 'Todos los niveles',
    duration: '60 min',
    energy: 4,
    photo: 'comercial',
    decor: 'comercial',
    alt: 'Grupo bailando una coreografía comercial sincronizada con luces de neón rosas',
    highlight: 'Las coreografías de comercial son de las más aplaudidas en el festival de fin de curso.',
    lead: 'Las coreografías que ves en los videoclips y en los conciertos: comercial mezcla estilos urbanos, jazz y mucha actitud para bailar como una estrella del pop.',
    intro: [
      'Cada trimestre trabajamos canciones actuales con coreografías llenas de fuerza, formaciones y momentos de lucimiento. Es una clase exigente y muy divertida, donde se gana confianza a toda velocidad.',
      'Aprenderás a limpiar movimientos, a trabajar el «face» y la proyección, y a moverte en grupo con la sincronía de un cuerpo de baile profesional.',
    ],
    learn: [
      ['Estilo jazz-funk', 'Líneas, poses y fuerza al estilo de los grandes shows.'],
      ['Sincronía', 'Bailar en grupo como un solo cuerpo.'],
      ['Formaciones', 'Cambios de posición y uso del espacio escénico.'],
      ['Proyección', 'Mirada, gesto y actitud para llegar al público.'],
      ['Limpieza', 'Detalle en cada movimiento: ángulos, finales y acentos.'],
      ['Memoria', 'Aprender coreografías largas de forma rápida.'],
    ],
    session: [
      ['10 min', 'Calentamiento', 'Cardio, movilidad y grooves.'],
      ['10 min', 'Técnica', 'Giros, poses y ejercicios de estilo.'],
      ['30 min', 'Coreografía', 'La canción del momento, bloque a bloque.'],
      ['10 min', 'Grabación', 'Bailamos y grabamos para ver la evolución.'],
    ],
    forWho: ['Fans del pop y los videoclips', 'Jóvenes que quieren escenario', 'Adultos que quieren ganar seguridad', 'Quien viene de otros estilos y busca más actitud'],
    wear: commonWear.urbano,
    levels: [
      ['Iniciación', 'Coreografías asequibles para ganar soltura.'],
      ['Intermedio', 'Más velocidad, detalles y formaciones.'],
      ['Avanzado', 'Piezas de exhibición y certámenes.'],
    ],
    faq: [
      ['¿Qué música se baila?', 'Pop y urbano actual: lo que suena en radio y plataformas, adaptado a cada edad.'],
      ['¿Es parecido al funky?', 'Comparten energía, pero comercial tiene más influencia del jazz y del espectáculo.'],
      ['¿Se graban las coreografías?', 'A veces, para que veas tu progreso. Solo si te parece bien.'],
    ],
  },
  {
    slug: 'k-pop',
    name: 'K-Pop',
    menu: 'Covers de tus grupos favoritos',
    tagline: 'Coreografías vibrantes al ritmo del pop coreano.',
    title: 'K-Pop <em>dance cover</em>',
    group: 'urbano',
    tags: ['peques', 'jovenes'],
    ages: 'Desde 8 años · infantil y juvenil',
    level: 'Todos los niveles',
    duration: '60 min',
    energy: 4,
    photo: 'k-pop',
    decor: 'k-pop',
    alt: 'Grupo de jóvenes bailando una coreografía de K-pop en un estudio rosado',
    highlight: 'Aprende las coreografías originales de tus grupos favoritos, con su energía y su precisión.',
    lead: 'Las coreografías de K-pop son famosas por su energía y su precisión milimétrica. En esta clase aprendemos los dance covers de los grupos que más te gustan.',
    intro: [
      'Trabajamos las coreografías originales —o adaptadas al nivel— de las canciones del momento, con atención a los detalles que hacen especial a este estilo: sincronía perfecta, gestos de cámara y formaciones constantes.',
      'Es un espacio para compartir fandom, hacer amigos y perder la vergüenza bailando lo que más te gusta.',
    ],
    learn: [
      ['Dance covers', 'Coreografías originales paso a paso.'],
      ['Precisión', 'Ángulos, tiempos y finales exactos como en los vídeos.'],
      ['Formaciones', 'Cambios de posición rápidos y limpios.'],
      ['Expresión', 'Gestos, miradas y «killing parts».'],
      ['Resistencia', 'Bailar canciones completas sin perder energía.'],
      ['Trabajo en equipo', 'Cada miembro cuenta para que el cover brille.'],
    ],
    session: [
      ['10 min', 'Calentamiento', 'Movilidad y cardio con playlist K-pop.'],
      ['10 min', 'Básicos', 'Pasos y grooves característicos.'],
      ['30 min', 'Cover', 'La coreografía de la canción elegida.'],
      ['10 min', 'Pasada', 'Bailamos el cover completo en formación.'],
    ],
    forWho: ['Fans del K-pop desde 8 años', 'Adolescentes que quieren bailar en grupo', 'Quien busca hacer amigos con los mismos gustos', 'Principiantes y bailarines con experiencia'],
    wear: commonWear.urbano,
    levels: [
      ['Infantil', 'Covers adaptados y canciones elegidas para su edad.'],
      ['Juvenil', 'Coreografías originales con más dificultad.'],
      ['Crew', 'Preparación de covers para exhibiciones.'],
    ],
    faq: [
      ['¿Podemos proponer canciones?', '¡Claro! Las canciones se eligen entre todo el grupo cada trimestre.'],
      ['¿Hay que saber bailar?', 'No. Se aprende desde cero y a tu ritmo.'],
      ['¿Hay K-pop para adultos?', 'Pregúntanos: si hay grupo suficiente, se abre.'],
    ],
  },
  {
    slug: 'salsa',
    name: 'Salsa y salón',
    menu: 'Bailes de salón y en pareja',
    tagline: 'Déjate llevar por el ritmo, en pareja o en rueda.',
    title: 'Salsa y <em>bailes de salón</em>',
    group: 'ritmo',
    tags: ['adultos', 'parejas'],
    ages: 'Adultos · con o sin pareja',
    level: 'Iniciación e intermedio',
    duration: '60 min',
    energy: 3,
    photo: 'salsa',
    decor: 'salsa',
    alt: 'Pareja bailando salsa en una sala de baile con suelo de madera y luz cálida',
    highlight: 'Salón es uno de los estilos que la escuela anuncia desde siempre: salsa, bachata, merengue, pasodoble…',
    lead: 'Salsa, bachata, merengue, chachachá o pasodoble. Los bailes de salón y latinos son la mejor forma de disfrutar de la música en compañía y de no quedarte nunca sentado en una boda.',
    intro: [
      'Aprendemos a llevar y a dejarse llevar, a escuchar la clave y a encadenar figuras con naturalidad. Puedes venir en pareja o solo: en clase se rota para que todo el mundo baile con todo el mundo.',
      'Es una clase social, alegre y muy agradecida, en la que en pocas semanas ya te sientes capaz de salir a bailar.',
    ],
    learn: [
      ['Básicos', 'El paso base de cada ritmo, bien marcado.'],
      ['Conducción', 'Llevar y seguir con claridad y suavidad.'],
      ['Figuras', 'Vueltas, cruces y combinaciones encadenadas.'],
      ['Musicalidad', 'Encontrar el «uno» y bailar a tempo.'],
      ['Estilo', 'Brazos, cadera y presencia para bailar bonito.'],
      ['Bailes de salón', 'Pasodoble, chachachá, vals o tango según el grupo.'],
    ],
    session: [
      ['10 min', 'Calentamiento', 'Paso básico y ritmo individual.'],
      ['15 min', 'Técnica', 'Conducción y figura nueva de la semana.'],
      ['25 min', 'En pareja', 'Combinaciones con rotación de pareja.'],
      ['10 min', 'Social', 'Bailamos libre con toda la clase.'],
    ],
    forWho: ['Parejas que quieren un plan juntos', 'Personas que vienen solas a conocer gente', 'Invitados que quieren lucirse en una boda', 'Quien busca un ejercicio alegre y social'],
    wear: ['Ropa cómoda en la que te sientas bien', 'Zapato que gire: suela lisa o de baile', 'Evita la suela de goma', 'Agua y buen humor'],
    levels: [
      ['Iniciación', 'Básicos de salsa, bachata y merengue.'],
      ['Intermedio', 'Figuras encadenadas, giros y estilo.'],
      ['Salón', 'Pasodoble, chachachá, vals y más.'],
    ],
    faq: [
      ['¿Necesito pareja?', 'No. Se rota durante la clase y siempre hay con quien bailar.'],
      ['¿Qué estilos se aprenden?', 'Sobre todo salsa y bachata, y bailes de salón según el grupo y el trimestre.'],
      ['¿Me sirve para la boda de un amigo?', '¡Totalmente! Y si eres quien se casa, mira nuestro baile nupcial.'],
    ],
  },
  {
    slug: 'zumba',
    name: 'Zumba',
    menu: 'Fiesta fitness con ritmos latinos',
    tagline: 'Música, movimiento y ganas de bailar.',
    title: 'Zumba, <em>pura fiesta</em>',
    group: 'ritmo',
    tags: ['adultos'],
    ages: 'Adultos',
    level: 'Sin experiencia',
    duration: '60 min',
    energy: 5,
    photo: 'zumba',
    decor: 'cintas',
    alt: 'Grupo de adultos sonriendo durante una clase de zumba llena de energía',
    highlight: 'Una hora de música y baile en la que se te olvida que estás haciendo ejercicio.',
    lead: 'Ritmos latinos, reguetón, cumbia y pop en una sesión que es medio clase de baile, medio fiesta. Zumba es la forma más divertida de ponerse en forma.',
    intro: [
      'Coreografías sencillas que se repiten y se aprenden sin darte cuenta, con una intensidad que cada persona adapta a su forma física. No hace falta saber bailar: solo dejarse llevar.',
      'Ideal para desconectar después del trabajo, ganar resistencia y salir con la energía por las nubes.',
    ],
    learn: [
      ['Cardio', 'Mejorar la resistencia sin darte cuenta.'],
      ['Coordinación', 'Brazos y piernas a la vez, cada vez con más soltura.'],
      ['Ritmos latinos', 'Salsa, merengue, cumbia y reguetón en clave fitness.'],
      ['Tono muscular', 'Piernas, glúteos y abdomen trabajan en cada canción.'],
      ['Desconexión', 'Una hora para ti, con música y buena compañía.'],
      ['Constancia', 'Una rutina que apetece repetir.'],
    ],
    session: [
      ['5 min', 'Activación', 'Canciones suaves para entrar en calor.'],
      ['25 min', 'Subida', 'Coreografías de alta energía.'],
      ['20 min', 'Tonificación', 'Canciones con más trabajo de piernas y core.'],
      ['10 min', 'Calma', 'Bajamos pulsaciones y estiramos.'],
    ],
    forWho: ['Adultos de cualquier edad y forma física', 'Quien se aburre en el gimnasio', 'Grupos de amigas y amigos', 'Quien quiere moverse sin presión técnica'],
    wear: ['Ropa deportiva transpirable', 'Zapatillas de deporte con buena amortiguación', 'Toalla y agua', 'Ganas de reír'],
    levels: [
      ['Para todos', 'Cada persona regula la intensidad.'],
      ['Opción suave', 'Variantes de bajo impacto en cada canción.'],
      ['Opción intensa', 'Saltos y más recorrido para quien quiere más.'],
    ],
    faq: [
      ['¿Tengo que estar en forma?', 'No. Cada canción tiene versión suave y versión intensa.'],
      ['¿Se aprenden coreografías difíciles?', 'No: son sencillas y repetitivas, para disfrutar desde el primer día.'],
      ['¿Cuántas calorías se queman?', 'Depende de cada persona, pero es una sesión de cardio completa.'],
    ],
  },
  {
    slug: 'country',
    name: 'Country',
    menu: 'Line dance en buena compañía',
    tagline: 'Ritmo, pasos y sabor country para bailar en compañía.',
    title: 'Country <em>line dance</em>',
    group: 'ritmo',
    tags: ['adultos', 'jovenes'],
    ages: 'Jóvenes y adultos',
    level: 'Iniciación e intermedio',
    duration: '60 min',
    energy: 3,
    photo: 'country',
    decor: 'country',
    alt: 'Grupo de personas con sombrero vaquero bailando country en línea',
    highlight: 'No necesitas pareja: en el country se baila en línea, todos a la vez.',
    lead: 'El baile en línea es contagioso: todos a la vez, mirando a la misma pared, con pasos que se repiten y música que hace sonreír. No necesitas pareja ni experiencia.',
    intro: [
      'Aprendemos coreografías de line dance —con sus vine, shuffles, rock steps y kick ball changes— sobre música country, pop-country y canciones actuales.',
      'Es una de las clases con mejor ambiente: un plan social, perfecto para ejercitar la memoria y la coordinación mientras te ríes con el grupo.',
    ],
    learn: [
      ['Pasos base', 'Vine, shuffle, rock step, pivot y coaster.'],
      ['Line dances', 'Coreografías completas de las más bailadas.'],
      ['Memoria', 'Secuencias que se encadenan y entrenan la mente.'],
      ['Coordinación', 'Pies rápidos y ritmo constante.'],
      ['Musicalidad', 'Contar en 8 y entrar a tiempo.'],
      ['Ambiente', 'Bailar en grupo y compartir.'],
    ],
    session: [
      ['10 min', 'Repaso', 'Bailamos los line dances ya aprendidos.'],
      ['15 min', 'Pasos', 'Técnica de los pasos nuevos.'],
      ['25 min', 'Coreografía', 'Nueva coreografía, pared a pared.'],
      ['10 min', 'Baile libre', 'Ponemos la lista y a bailar.'],
    ],
    forWho: ['Adultos que quieren un plan social', 'Quien no tiene pareja de baile', 'Amantes de la música country', 'Personas que buscan ejercitar memoria y coordinación'],
    wear: ['Ropa cómoda', 'Botas camperas o zapato con suela que deslice', 'Sombrero opcional (¡pero queda genial!)', 'Agua'],
    levels: [
      ['Iniciación', 'Pasos básicos y coreografías cortas.'],
      ['Intermedio', 'Coreografías más largas y con giros.'],
      ['Social', 'Bailes populares para quedadas y eventos.'],
    ],
    faq: [
      ['¿Necesito botas?', 'No hace falta. Un zapato cómodo que gire bien es suficiente.'],
      ['¿Hay que ir en pareja?', 'No: el line dance se baila de forma individual, en grupo.'],
      ['¿Es difícil?', 'Los pasos se repiten mucho, así que se aprende rápido.'],
    ],
  },
]

export const BODAS = {
  slug: 'baile-nupcial',
  name: 'Baile nupcial',
  menu: 'Vuestro primer baile, a medida',
  tagline: 'El primer baile de vuestra vida juntos, coreografiado a medida.',
  title: 'Vuestro <em>primer baile</em>',
  tags: ['parejas', 'adultos'],
  ages: 'Parejas · sin experiencia',
  level: 'A medida',
  duration: 'Unas 10 clases',
  energy: 2,
  photo: 'bodas-wide',
  decor: 'baile-moderno',
  alt: 'Pareja bailando en una sala con luz cálida, ella con vestido rosa que vuela al girar',
  lead: 'Elegís la canción y nosotras hacemos el resto. Manuela crea una coreografía pensada para vosotros, para vuestro nivel y para el espacio del banquete.',
  intro: [
    'Lo dicen las parejas que ya han pasado por la escuela: en unas diez clases se monta un baile precioso, y hay muchísimas facilidades para cuadrar horarios incluso cuando la boda está a la vuelta de la esquina.',
    'Podéis elegir un baile romántico, un vals, una bachata, una sevillana o un mashup sorpresa que empieza lento y explota a mitad de canción. Todo es posible.',
  ],
  steps: [
    ['01', 'Primera cita', 'Nos contáis la canción, la fecha, cómo será el vestido y qué os gustaría transmitir.'],
    ['02', 'Coreografía a medida', 'Manuela diseña un baile adaptado a vuestro nivel, a la música y al espacio del banquete.'],
    ['03', 'Ensayos', 'Unas diez clases privadas, con horarios flexibles, para aprenderlo sin agobios.'],
    ['04', 'Ensayo general', 'Practicamos con el calzado y, si se puede, con algo parecido al vestido.'],
    ['05', 'El gran día', 'Salís a la pista sabiendo lo que hacéis y disfrutándolo. Y nos mandáis el vídeo.'],
  ],
  extras: [
    ['Canción', 'Romántica, latina, flamenca, clásica o un mashup sorpresa.'],
    ['Horarios', 'Flexibles: entre semana, tarde o fin de semana según disponibilidad.'],
    ['Padrinos e invitados', 'También montamos el baile con padrinos, damas de honor o la familia.'],
    ['Sevillanas de boda', 'Clases exprés para que todos los invitados se animen.'],
  ],
  faq: [
    ['¿Con cuánta antelación hay que empezar?', 'Lo ideal es unos dos o tres meses antes, pero se han montado bailes espectaculares con muy poco tiempo.'],
    ['¿Y si no hemos bailado nunca?', 'Es lo más habitual. La coreografía se adapta a vosotros, no al revés.'],
    ['¿Cuántas clases hacen falta?', 'Depende de la canción y del nivel, pero en torno a diez clases suele ser suficiente.'],
    ['¿Podemos hacer un baile sorpresa?', '¡Claro! Los mashups con cambio de canción son de lo más pedido.'],
  ],
}

// Reseñas reales de Google (texto literal)
export const REVIEWS = [
  { name: 'Andrea Jiménez', when: 'hace 3 años', rating: 5, tag: 'Baile nupcial', text: 'Manuela es una gran profesional y una profesora excepcional. En 10 clases nos montó el baile nupcial y fue maravilloso. Coreografía preciosa y encima, muchísimas facilidades para cuadrar horarios ¡La recomendamos sin ninguna duda!' },
  { name: 'Alba M', when: 'hace 2 años', rating: 5, tag: 'Alumna', text: 'Escuela de danza familiar de varias disciplinas en las que, tanto Inés como Manuela, desde el primer minuto te hacen amar la danza.' },
  { name: 'Javier Lasser', when: 'hace 7 años', rating: 5, tag: 'Baile nupcial', text: 'Simplemente excelente. Muy profesionales. Encargamos con muy poquito tiempo un baile nupcial y salió espectacular. Manuela quedará también en nuestro recuerdo de boda 👏🏻👏🏻👏🏻👏🏻❤️' },
  { name: 'cintia', when: 'hace 9 meses', rating: 5, tag: 'Familia', text: 'La escuela de danza de Manuela es muy familiar, cercana y profesional. Muy recomendable.' },
  { name: 'Rocio Villafañez Gutierrez', when: 'hace 3 años', rating: 5, tag: 'Familia', text: 'La mejor escuela de baile, súper profesionales, arte, dedicación... No hay mejor sitio donde l@s peques aprendan y se diviertan. 🥰' },
  { name: 'ruth castillo', when: 'hace 3 años', rating: 5, tag: 'Familia', text: 'Mi niña a comenzado en la escuela de danza de Manuela y está muy contenta, es una maravilla Manuela muy amable y excelente profesional' },
  { name: 'Diana Velasco', when: 'hace 5 años', rating: 5, tag: 'Alumna', text: 'Genial, son muy amables, profesionales y con muy buen ambiente. Diversión dentro de la danza garantizada!! Las actuaciones son buenísimas, 100% recomendable.' },
  { name: 'M Esther Gallo Martinez', when: 'hace 5 años', rating: 5, tag: 'Flamenco', text: 'Un lujo al alcance de todos con la mejor profesional de flamenco de Madrid.' },
  { name: 'María Ángeles F.F.', when: 'hace 5 años', rating: 5, tag: 'Alumna', text: 'Un lugar ideal para disfrutar del baile, tanto los profesores como los alumnos hacen del aprendizaje una diversión. Totalmente recomendable.' },
  { name: 'lucia gimenez', when: 'hace 6 años', rating: 5, tag: 'Alumna', text: 'Un lugar donde puedes sacar tu talento aunque te cueste un poco adaptarte al final se pasa muy bien la experiencia' },
  { name: 'Sandra', when: 'hace 4 años', rating: 5, tag: 'Alumna', text: 'Son todas un encanto. De 10' },
]

export const STATS = [
  { value: 4.7, decimals: 1, suffix: '★', label: 'Valoración en Google', sub: '21 reseñas' },
  { value: 10, suffix: '', label: 'Estilos de danza', sub: 'de ballet a K-pop' },
  { value: 2, suffix: 'ª', label: 'Posición en el Campeonato de España', sub: 'Liryc y Blackfunk' },
  { value: 2, suffix: '', label: 'Sedes en Madrid', sub: 'San Blas-Canillejas' },
]

export const MILESTONES = [
  { kicker: 'Campeonato de España', title: 'Subcampeonas en su categoría', text: 'Los grupos Liryc (lírico) y Blackfunk (funky) se clasificaron en segunda posición de su categoría. «¡Enhorabuena, dancers!»' },
  { kicker: 'Certamen Bailando a la Vida', title: 'La magia de la escuela, en escena', text: 'Nuestras alumnas llevaron sus coreografías al certamen Bailando a la Vida en primavera de 2025.' },
  { kicker: 'Festival de fin de curso', title: 'Vuestro sitio en el escenario', text: 'Cada curso termina con un festival en el que todos los grupos —de predanza a adultos— suben al escenario.' },
  { kicker: 'Actuaciones en Madrid', title: 'Bailar fuera del aula', text: 'Exhibiciones, fiestas de barrio y eventos: la escuela participa en actuaciones por Madrid durante todo el año.' },
]

export const TEAM = [
  { name: 'Manuela', role: 'Directora y profesora', text: 'Fundadora de la escuela y alma del flamenco en ella. Sus alumnas y las parejas que han bailado con ella destacan lo mismo: profesionalidad, cercanía y una forma de enseñar que hace amar la danza.', img: 'flamenco' },
  { name: 'Inés', role: 'Profesora', text: 'Parte del equipo que, como cuentan las propias alumnas, «desde el primer minuto te hace amar la danza». Con un equipo renovado, cada estilo tiene su especialista.', img: 'ballet' },
]

export const VALUES = [
  ['Familiar', 'Una escuela de barrio donde se conoce a cada alumna y alumno por su nombre.'],
  ['Profesional', 'Técnica cuidada, progresión real y preparación para competir si se desea.'],
  ['Para todas las edades', 'De la predanza a los 4 años a los grupos de adultos.'],
  ['Con escenario', 'Festival, certámenes y actuaciones: la danza se comparte.'],
]

// Horario de EJEMPLO (día 0 = lunes). Sustituir por el horario real.
export const SCHEDULE = [
  { day: 0, start: '17:00', end: '18:00', slug: 'ballet', group: 'Predanza 4–6 años', sede: 'canillejas' },
  { day: 0, start: '18:00', end: '19:00', slug: 'funky', group: 'Infantil 7–11 años', sede: 'canillejas' },
  { day: 0, start: '19:00', end: '20:00', slug: 'flamenco', group: 'Adultos iniciación', sede: 'canillejas' },
  { day: 0, start: '20:00', end: '21:00', slug: 'zumba', group: 'Adultos', sede: 'longares' },
  { day: 1, start: '17:30', end: '18:30', slug: 'flamenco', group: 'Infantil', sede: 'canillejas' },
  { day: 1, start: '18:30', end: '19:30', slug: 'k-pop', group: 'Juvenil 10–15 años', sede: 'canillejas' },
  { day: 1, start: '19:30', end: '20:30', slug: 'baile-moderno', group: 'Contemporáneo · Liryc', sede: 'longares' },
  { day: 1, start: '20:30', end: '21:30', slug: 'salsa', group: 'Salsa y bachata', sede: 'longares' },
  { day: 2, start: '17:00', end: '18:00', slug: 'ballet', group: 'Clásico infantil', sede: 'canillejas' },
  { day: 2, start: '18:00', end: '19:00', slug: 'comercial', group: 'Juvenil', sede: 'canillejas' },
  { day: 2, start: '19:00', end: '20:00', slug: 'funky', group: 'Adultos · Blackfunk', sede: 'canillejas' },
  { day: 2, start: '20:00', end: '21:00', slug: 'country', group: 'Line dance', sede: 'longares' },
  { day: 3, start: '17:30', end: '18:30', slug: 'flamenco', group: 'Juvenil', sede: 'canillejas' },
  { day: 3, start: '18:30', end: '19:30', slug: 'ballet', group: 'Lírico y puntas', sede: 'canillejas' },
  { day: 3, start: '19:30', end: '20:30', slug: 'zumba', group: 'Adultos', sede: 'longares' },
  { day: 3, start: '20:30', end: '21:30', slug: 'flamenco', group: 'Adultos · sevillanas', sede: 'canillejas' },
  { day: 4, start: '17:00', end: '18:00', slug: 'k-pop', group: 'Infantil 8–11 años', sede: 'canillejas' },
  { day: 4, start: '18:00', end: '19:00', slug: 'funky', group: 'Juvenil', sede: 'canillejas' },
  { day: 4, start: '19:00', end: '20:00', slug: 'salsa', group: 'Salón · iniciación', sede: 'longares' },
  { day: 5, start: '10:30', end: '11:30', slug: 'ballet', group: 'Ballet adultos', sede: 'canillejas' },
  { day: 5, start: '11:30', end: '12:30', slug: 'baile-moderno', group: 'Moderno juvenil', sede: 'canillejas' },
  { day: 5, start: '12:30', end: '13:30', slug: 'baile-nupcial', group: 'Parejas · con cita', sede: 'canillejas' },
]
export const DAYS = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado']

export const FAQ = [
  ['¿Puedo hacer una clase de prueba?', 'Escríbenos por WhatsApp o llámanos y te contamos cómo probar la clase que te interesa antes de apuntarte.'],
  ['¿Desde qué edad se puede empezar?', 'Desde los 4 años en predanza y ballet. Hay grupos infantiles, juveniles y de adultos en casi todos los estilos.'],
  ['¿Cuándo empieza el curso?', 'El curso arranca en septiembre, pero puedes incorporarte durante el año si hay plaza en tu grupo.'],
  ['¿Cuánto cuestan las clases?', 'Depende del estilo y del número de horas a la semana. Pregúntanos y te pasamos las tarifas actualizadas.'],
  ['¿Tengo que tener experiencia?', 'No. Todos los estilos tienen grupo de iniciación y la progresión se adapta a cada persona.'],
  ['¿Dónde están las sedes?', 'En Av. de Canillejas a Vicálvaro, 139 y en C/ Longares, 48, las dos en San Blas-Canillejas (Madrid).'],
  ['¿Hay actuaciones?', 'Sí: festival de fin de curso, certámenes y actuaciones por Madrid. Participar es voluntario.'],
  ['¿Hacéis bailes para bodas?', 'Sí, coreografías de baile nupcial a medida, con horarios flexibles.'],
]

export const QUIZ = [
  {
    q: '¿Para quién es la clase?',
    options: [
      ['Para un peque (4–11 años)', { ballet: 3, funky: 3, flamenco: 2, 'k-pop': 2 }],
      ['Para un adolescente', { 'k-pop': 3, comercial: 3, funky: 2, 'baile-moderno': 2 }],
      ['Para mí (adulto)', { zumba: 2, salsa: 2, flamenco: 2, country: 2, 'baile-moderno': 1, ballet: 1 }],
      ['Para nosotros, que nos casamos', { 'baile-nupcial': 6, salsa: 2 }],
    ],
  },
  {
    q: '¿Qué energía te apetece?',
    options: [
      ['Elegante y tranquila', { ballet: 3, 'baile-moderno': 2, 'baile-nupcial': 1 }],
      ['Con arte y carácter', { flamenco: 3, salsa: 2 }],
      ['Urbana y con actitud', { funky: 3, comercial: 2, 'k-pop': 2 }],
      ['Sudar y pasarlo bomba', { zumba: 3, country: 1, funky: 1 }],
    ],
  },
  {
    q: '¿Qué música te mueve?',
    options: [
      ['Clásica o emotiva', { ballet: 3, 'baile-moderno': 3 }],
      ['Flamenco y rumba', { flamenco: 4 }],
      ['Pop, urbano o K-pop', { 'k-pop': 3, comercial: 3, funky: 2 }],
      ['Latina o country', { salsa: 3, zumba: 2, country: 3 }],
    ],
  },
]
